### ISSUE TITLE
能否添加一个图片格式的过滤呢？比如不显示GIF

### ISSUE THREAD

**Issue by andansky** [jeasonlzy0216/ImagePicker#28]

**Comment by hust201010701** [comment]
你可以修改ImageDataSource.java中的onCreateLoader方法。


    @Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        CursorLoader cursorLoader = null;
        //扫描所有图片
        if (id == LOADER_ALL)
			//cursorLoader = new CursorLoader(activity, MediaStore.Images.Media.EXTERNAL_CONTENT_URI, 
			IMAGE_PROJECTION, null, null, IMAGE_PROJECTION[6] + " DESC");//修改为下面这句话
            cursorLoader = new CursorLoader(activity, MediaStore.Images.Media.EXTERNAL_CONTENT_URI, 
			IMAGE_PROJECTION, MediaStore.Images.Media.DISPLAY_NAME + " NOT LIKE ?", new String[] { "%gif" }, IMAGE_PROJECTION[6] + " DESC");
        //扫描某个图片文件夹
        if (id == LOADER_CATEGORY)
            cursorLoader = new CursorLoader(activity, MediaStore.Images.Media.EXTERNAL_CONTENT_URI, IMAGE_PROJECTION, IMAGE_PROJECTION[1] + " like '%" + args.getString("path") + "%'", null, IMAGE_PROJECTION[6] + " DESC");

        return cursorLoader;
    }

这样就可以选择不含gif格式的图片。

**Comment by jeasonlzy0216** [comment]
这个是个定制化的需求。可能有其他人需求。

**Comment by andansky** [comment]
好的，谢谢。

**Comment by lancewong2014** [comment]
我觉得应该给一个过滤接口出来。方便定制。
