### ISSUE TITLE
ImagePicker 图库中文件名包含%符号 无法识别和显示

### ISSUE THREAD

**Issue by z8806c** [jeasonlzy0216/ImagePicker#8]
ImagePicker 图库中文件名包含%符号 无法识别和显示

**Comment by ikkong** [comment]
这个问题我找到答案了
` Glide.with(activity).load("file://" + path)                  //设置图片路径
`
改为
`Glide.with(activity).load(Uri.fromFile(new File(path)))//设置图片路径`
即可
详见[https://github.com/bumptech/glide/issues/867](url)
@jeasonlzy0216

**Comment by jeasonlzy0216** [comment]
@ikkong 感谢。已升级修复 版本 0.2.6
